#Pod Uses Service Account Token from Service Account to Authenticate the K8S Api Server and By default if its not mentioned then it uses the default service account token 
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod1
  name: pod1
spec:
  serviceAccountName: service1
  containers:
  - image: httpd
    name: pod1
